// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestTask.Database;

#nullable disable

namespace TestTask.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestTask.Database.Entities.Rectangle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("X1")
                        .HasColumnType("int");

                    b.Property<int>("X2")
                        .HasColumnType("int");

                    b.Property<int>("Y1")
                        .HasColumnType("int");

                    b.Property<int>("Y2")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("X1", "Y1", "X2", "Y2")
                        .IsUnique();

                    b.ToTable("Rectangle", "Rectangle", t =>
                        {
                            t.HasCheckConstraint("CK_Rectangle_XY_Check", "X1 < X2 AND Y1 < Y2");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            X1 = 8,
                            X2 = 194,
                            Y1 = 57,
                            Y2 = 110
                        },
                        new
                        {
                            Id = 2L,
                            X1 = 23,
                            X2 = 186,
                            Y1 = 78,
                            Y2 = 108
                        },
                        new
                        {
                            Id = 3L,
                            X1 = 29,
                            X2 = 48,
                            Y1 = 10,
                            Y2 = 116
                        },
                        new
                        {
                            Id = 4L,
                            X1 = 69,
                            X2 = 148,
                            Y1 = 81,
                            Y2 = 141
                        },
                        new
                        {
                            Id = 5L,
                            X1 = 68,
                            X2 = 149,
                            Y1 = 43,
                            Y2 = 115
                        },
                        new
                        {
                            Id = 6L,
                            X1 = 91,
                            X2 = 124,
                            Y1 = 41,
                            Y2 = 114
                        },
                        new
                        {
                            Id = 7L,
                            X1 = 41,
                            X2 = 192,
                            Y1 = 28,
                            Y2 = 186
                        },
                        new
                        {
                            Id = 8L,
                            X1 = 95,
                            X2 = 98,
                            Y1 = 9,
                            Y2 = 83
                        },
                        new
                        {
                            Id = 9L,
                            X1 = 68,
                            X2 = 114,
                            Y1 = 79,
                            Y2 = 132
                        },
                        new
                        {
                            Id = 10L,
                            X1 = 1,
                            X2 = 93,
                            Y1 = 51,
                            Y2 = 59
                        },
                        new
                        {
                            Id = 11L,
                            X1 = 99,
                            X2 = 137,
                            Y1 = 55,
                            Y2 = 175
                        },
                        new
                        {
                            Id = 12L,
                            X1 = 60,
                            X2 = 178,
                            Y1 = 18,
                            Y2 = 183
                        },
                        new
                        {
                            Id = 13L,
                            X1 = 97,
                            X2 = 131,
                            Y1 = 88,
                            Y2 = 187
                        },
                        new
                        {
                            Id = 14L,
                            X1 = 18,
                            X2 = 198,
                            Y1 = 25,
                            Y2 = 185
                        },
                        new
                        {
                            Id = 15L,
                            X1 = 36,
                            X2 = 121,
                            Y1 = 41,
                            Y2 = 146
                        },
                        new
                        {
                            Id = 16L,
                            X1 = 83,
                            X2 = 158,
                            Y1 = 33,
                            Y2 = 62
                        },
                        new
                        {
                            Id = 17L,
                            X1 = 46,
                            X2 = 146,
                            Y1 = 46,
                            Y2 = 120
                        },
                        new
                        {
                            Id = 18L,
                            X1 = 66,
                            X2 = 74,
                            Y1 = 45,
                            Y2 = 54
                        },
                        new
                        {
                            Id = 19L,
                            X1 = 37,
                            X2 = 164,
                            Y1 = 71,
                            Y2 = 155
                        },
                        new
                        {
                            Id = 20L,
                            X1 = 14,
                            X2 = 90,
                            Y1 = 71,
                            Y2 = 150
                        },
                        new
                        {
                            Id = 21L,
                            X1 = 61,
                            X2 = 79,
                            Y1 = 98,
                            Y2 = 166
                        },
                        new
                        {
                            Id = 22L,
                            X1 = 39,
                            X2 = 40,
                            Y1 = 59,
                            Y2 = 142
                        },
                        new
                        {
                            Id = 23L,
                            X1 = 57,
                            X2 = 180,
                            Y1 = 75,
                            Y2 = 112
                        },
                        new
                        {
                            Id = 24L,
                            X1 = 40,
                            X2 = 108,
                            Y1 = 68,
                            Y2 = 134
                        },
                        new
                        {
                            Id = 25L,
                            X1 = 51,
                            X2 = 135,
                            Y1 = 5,
                            Y2 = 187
                        },
                        new
                        {
                            Id = 26L,
                            X1 = 41,
                            X2 = 81,
                            Y1 = 38,
                            Y2 = 101
                        },
                        new
                        {
                            Id = 27L,
                            X1 = 74,
                            X2 = 116,
                            Y1 = 93,
                            Y2 = 141
                        },
                        new
                        {
                            Id = 28L,
                            X1 = 32,
                            X2 = 119,
                            Y1 = 8,
                            Y2 = 89
                        },
                        new
                        {
                            Id = 29L,
                            X1 = 89,
                            X2 = 94,
                            Y1 = 21,
                            Y2 = 123
                        },
                        new
                        {
                            Id = 30L,
                            X1 = 8,
                            X2 = 13,
                            Y1 = 68,
                            Y2 = 154
                        },
                        new
                        {
                            Id = 31L,
                            X1 = 31,
                            X2 = 148,
                            Y1 = 16,
                            Y2 = 148
                        },
                        new
                        {
                            Id = 32L,
                            X1 = 56,
                            X2 = 93,
                            Y1 = 70,
                            Y2 = 137
                        },
                        new
                        {
                            Id = 33L,
                            X1 = 22,
                            X2 = 107,
                            Y1 = 54,
                            Y2 = 184
                        },
                        new
                        {
                            Id = 34L,
                            X1 = 29,
                            X2 = 145,
                            Y1 = 20,
                            Y2 = 25
                        },
                        new
                        {
                            Id = 35L,
                            X1 = 84,
                            X2 = 184,
                            Y1 = 91,
                            Y2 = 144
                        },
                        new
                        {
                            Id = 36L,
                            X1 = 17,
                            X2 = 51,
                            Y1 = 56,
                            Y2 = 79
                        },
                        new
                        {
                            Id = 37L,
                            X1 = 32,
                            X2 = 167,
                            Y1 = 76,
                            Y2 = 152
                        },
                        new
                        {
                            Id = 38L,
                            X1 = 96,
                            X2 = 112,
                            Y1 = 54,
                            Y2 = 198
                        },
                        new
                        {
                            Id = 39L,
                            X1 = 49,
                            X2 = 147,
                            Y1 = 94,
                            Y2 = 198
                        },
                        new
                        {
                            Id = 40L,
                            X1 = 62,
                            X2 = 168,
                            Y1 = 99,
                            Y2 = 175
                        },
                        new
                        {
                            Id = 41L,
                            X1 = 93,
                            X2 = 155,
                            Y1 = 6,
                            Y2 = 142
                        },
                        new
                        {
                            Id = 42L,
                            X1 = 26,
                            X2 = 118,
                            Y1 = 51,
                            Y2 = 144
                        },
                        new
                        {
                            Id = 43L,
                            X1 = 88,
                            X2 = 180,
                            Y1 = 44,
                            Y2 = 180
                        },
                        new
                        {
                            Id = 44L,
                            X1 = 85,
                            X2 = 184,
                            Y1 = 23,
                            Y2 = 184
                        },
                        new
                        {
                            Id = 45L,
                            X1 = 55,
                            X2 = 142,
                            Y1 = 67,
                            Y2 = 78
                        },
                        new
                        {
                            Id = 46L,
                            X1 = 22,
                            X2 = 144,
                            Y1 = 66,
                            Y2 = 147
                        },
                        new
                        {
                            Id = 47L,
                            X1 = 89,
                            X2 = 161,
                            Y1 = 86,
                            Y2 = 182
                        },
                        new
                        {
                            Id = 48L,
                            X1 = 20,
                            X2 = 47,
                            Y1 = 13,
                            Y2 = 150
                        },
                        new
                        {
                            Id = 49L,
                            X1 = 37,
                            X2 = 143,
                            Y1 = 69,
                            Y2 = 196
                        },
                        new
                        {
                            Id = 50L,
                            X1 = 87,
                            X2 = 173,
                            Y1 = 62,
                            Y2 = 178
                        },
                        new
                        {
                            Id = 51L,
                            X1 = 28,
                            X2 = 176,
                            Y1 = 76,
                            Y2 = 146
                        },
                        new
                        {
                            Id = 52L,
                            X1 = 49,
                            X2 = 131,
                            Y1 = 53,
                            Y2 = 70
                        },
                        new
                        {
                            Id = 53L,
                            X1 = 64,
                            X2 = 93,
                            Y1 = 21,
                            Y2 = 148
                        },
                        new
                        {
                            Id = 54L,
                            X1 = 76,
                            X2 = 82,
                            Y1 = 38,
                            Y2 = 96
                        },
                        new
                        {
                            Id = 55L,
                            X1 = 78,
                            X2 = 160,
                            Y1 = 73,
                            Y2 = 142
                        },
                        new
                        {
                            Id = 56L,
                            X1 = 97,
                            X2 = 128,
                            Y1 = 12,
                            Y2 = 178
                        },
                        new
                        {
                            Id = 57L,
                            X1 = 7,
                            X2 = 120,
                            Y1 = 42,
                            Y2 = 175
                        },
                        new
                        {
                            Id = 58L,
                            X1 = 1,
                            X2 = 66,
                            Y1 = 94,
                            Y2 = 96
                        },
                        new
                        {
                            Id = 59L,
                            X1 = 32,
                            X2 = 162,
                            Y1 = 79,
                            Y2 = 155
                        },
                        new
                        {
                            Id = 60L,
                            X1 = 63,
                            X2 = 155,
                            Y1 = 48,
                            Y2 = 132
                        },
                        new
                        {
                            Id = 61L,
                            X1 = 88,
                            X2 = 161,
                            Y1 = 10,
                            Y2 = 98
                        },
                        new
                        {
                            Id = 62L,
                            X1 = 25,
                            X2 = 144,
                            Y1 = 63,
                            Y2 = 74
                        },
                        new
                        {
                            Id = 63L,
                            X1 = 3,
                            X2 = 27,
                            Y1 = 39,
                            Y2 = 143
                        },
                        new
                        {
                            Id = 64L,
                            X1 = 50,
                            X2 = 197,
                            Y1 = 82,
                            Y2 = 159
                        },
                        new
                        {
                            Id = 65L,
                            X1 = 45,
                            X2 = 181,
                            Y1 = 86,
                            Y2 = 184
                        },
                        new
                        {
                            Id = 66L,
                            X1 = 14,
                            X2 = 116,
                            Y1 = 68,
                            Y2 = 168
                        },
                        new
                        {
                            Id = 67L,
                            X1 = 25,
                            X2 = 95,
                            Y1 = 4,
                            Y2 = 107
                        },
                        new
                        {
                            Id = 68L,
                            X1 = 36,
                            X2 = 131,
                            Y1 = 89,
                            Y2 = 196
                        },
                        new
                        {
                            Id = 69L,
                            X1 = 32,
                            X2 = 192,
                            Y1 = 97,
                            Y2 = 126
                        },
                        new
                        {
                            Id = 70L,
                            X1 = 14,
                            X2 = 176,
                            Y1 = 26,
                            Y2 = 117
                        },
                        new
                        {
                            Id = 71L,
                            X1 = 10,
                            X2 = 135,
                            Y1 = 84,
                            Y2 = 187
                        },
                        new
                        {
                            Id = 72L,
                            X1 = 23,
                            X2 = 30,
                            Y1 = 94,
                            Y2 = 185
                        },
                        new
                        {
                            Id = 73L,
                            X1 = 0,
                            X2 = 126,
                            Y1 = 21,
                            Y2 = 114
                        },
                        new
                        {
                            Id = 74L,
                            X1 = 38,
                            X2 = 87,
                            Y1 = 64,
                            Y2 = 90
                        },
                        new
                        {
                            Id = 75L,
                            X1 = 46,
                            X2 = 56,
                            Y1 = 15,
                            Y2 = 48
                        },
                        new
                        {
                            Id = 76L,
                            X1 = 55,
                            X2 = 145,
                            Y1 = 97,
                            Y2 = 131
                        },
                        new
                        {
                            Id = 77L,
                            X1 = 59,
                            X2 = 156,
                            Y1 = 10,
                            Y2 = 154
                        },
                        new
                        {
                            Id = 78L,
                            X1 = 51,
                            X2 = 195,
                            Y1 = 98,
                            Y2 = 135
                        },
                        new
                        {
                            Id = 79L,
                            X1 = 95,
                            X2 = 110,
                            Y1 = 79,
                            Y2 = 132
                        },
                        new
                        {
                            Id = 80L,
                            X1 = 42,
                            X2 = 99,
                            Y1 = 56,
                            Y2 = 170
                        },
                        new
                        {
                            Id = 81L,
                            X1 = 4,
                            X2 = 145,
                            Y1 = 85,
                            Y2 = 193
                        },
                        new
                        {
                            Id = 82L,
                            X1 = 21,
                            X2 = 189,
                            Y1 = 21,
                            Y2 = 134
                        },
                        new
                        {
                            Id = 83L,
                            X1 = 49,
                            X2 = 95,
                            Y1 = 5,
                            Y2 = 133
                        },
                        new
                        {
                            Id = 84L,
                            X1 = 38,
                            X2 = 140,
                            Y1 = 92,
                            Y2 = 127
                        },
                        new
                        {
                            Id = 85L,
                            X1 = 88,
                            X2 = 97,
                            Y1 = 27,
                            Y2 = 103
                        },
                        new
                        {
                            Id = 86L,
                            X1 = 64,
                            X2 = 71,
                            Y1 = 94,
                            Y2 = 147
                        },
                        new
                        {
                            Id = 87L,
                            X1 = 52,
                            X2 = 71,
                            Y1 = 7,
                            Y2 = 25
                        },
                        new
                        {
                            Id = 88L,
                            X1 = 26,
                            X2 = 64,
                            Y1 = 15,
                            Y2 = 143
                        },
                        new
                        {
                            Id = 89L,
                            X1 = 8,
                            X2 = 77,
                            Y1 = 3,
                            Y2 = 153
                        },
                        new
                        {
                            Id = 90L,
                            X1 = 54,
                            X2 = 122,
                            Y1 = 95,
                            Y2 = 110
                        },
                        new
                        {
                            Id = 91L,
                            X1 = 8,
                            X2 = 154,
                            Y1 = 54,
                            Y2 = 188
                        },
                        new
                        {
                            Id = 92L,
                            X1 = 57,
                            X2 = 158,
                            Y1 = 28,
                            Y2 = 173
                        },
                        new
                        {
                            Id = 93L,
                            X1 = 80,
                            X2 = 154,
                            Y1 = 19,
                            Y2 = 62
                        },
                        new
                        {
                            Id = 94L,
                            X1 = 52,
                            X2 = 190,
                            Y1 = 54,
                            Y2 = 71
                        },
                        new
                        {
                            Id = 95L,
                            X1 = 62,
                            X2 = 79,
                            Y1 = 70,
                            Y2 = 135
                        },
                        new
                        {
                            Id = 96L,
                            X1 = 31,
                            X2 = 107,
                            Y1 = 88,
                            Y2 = 96
                        },
                        new
                        {
                            Id = 97L,
                            X1 = 23,
                            X2 = 196,
                            Y1 = 58,
                            Y2 = 117
                        },
                        new
                        {
                            Id = 98L,
                            X1 = 70,
                            X2 = 80,
                            Y1 = 79,
                            Y2 = 156
                        },
                        new
                        {
                            Id = 99L,
                            X1 = 54,
                            X2 = 167,
                            Y1 = 34,
                            Y2 = 82
                        },
                        new
                        {
                            Id = 100L,
                            X1 = 22,
                            X2 = 164,
                            Y1 = 43,
                            Y2 = 76
                        },
                        new
                        {
                            Id = 101L,
                            X1 = 46,
                            X2 = 176,
                            Y1 = 69,
                            Y2 = 148
                        },
                        new
                        {
                            Id = 102L,
                            X1 = 97,
                            X2 = 135,
                            Y1 = 66,
                            Y2 = 163
                        },
                        new
                        {
                            Id = 103L,
                            X1 = 70,
                            X2 = 114,
                            Y1 = 98,
                            Y2 = 112
                        },
                        new
                        {
                            Id = 104L,
                            X1 = 28,
                            X2 = 142,
                            Y1 = 15,
                            Y2 = 193
                        },
                        new
                        {
                            Id = 105L,
                            X1 = 16,
                            X2 = 83,
                            Y1 = 32,
                            Y2 = 99
                        },
                        new
                        {
                            Id = 106L,
                            X1 = 90,
                            X2 = 197,
                            Y1 = 51,
                            Y2 = 130
                        },
                        new
                        {
                            Id = 107L,
                            X1 = 76,
                            X2 = 145,
                            Y1 = 89,
                            Y2 = 127
                        },
                        new
                        {
                            Id = 108L,
                            X1 = 71,
                            X2 = 114,
                            Y1 = 41,
                            Y2 = 120
                        },
                        new
                        {
                            Id = 109L,
                            X1 = 94,
                            X2 = 161,
                            Y1 = 2,
                            Y2 = 96
                        },
                        new
                        {
                            Id = 110L,
                            X1 = 27,
                            X2 = 65,
                            Y1 = 47,
                            Y2 = 114
                        },
                        new
                        {
                            Id = 111L,
                            X1 = 59,
                            X2 = 172,
                            Y1 = 14,
                            Y2 = 62
                        },
                        new
                        {
                            Id = 112L,
                            X1 = 23,
                            X2 = 81,
                            Y1 = 48,
                            Y2 = 61
                        },
                        new
                        {
                            Id = 113L,
                            X1 = 7,
                            X2 = 101,
                            Y1 = 82,
                            Y2 = 145
                        },
                        new
                        {
                            Id = 114L,
                            X1 = 94,
                            X2 = 147,
                            Y1 = 41,
                            Y2 = 94
                        },
                        new
                        {
                            Id = 115L,
                            X1 = 71,
                            X2 = 192,
                            Y1 = 80,
                            Y2 = 133
                        },
                        new
                        {
                            Id = 116L,
                            X1 = 15,
                            X2 = 190,
                            Y1 = 64,
                            Y2 = 80
                        },
                        new
                        {
                            Id = 117L,
                            X1 = 31,
                            X2 = 199,
                            Y1 = 30,
                            Y2 = 154
                        },
                        new
                        {
                            Id = 118L,
                            X1 = 1,
                            X2 = 117,
                            Y1 = 27,
                            Y2 = 118
                        },
                        new
                        {
                            Id = 119L,
                            X1 = 33,
                            X2 = 175,
                            Y1 = 49,
                            Y2 = 73
                        },
                        new
                        {
                            Id = 120L,
                            X1 = 42,
                            X2 = 97,
                            Y1 = 28,
                            Y2 = 174
                        },
                        new
                        {
                            Id = 121L,
                            X1 = 22,
                            X2 = 146,
                            Y1 = 99,
                            Y2 = 138
                        },
                        new
                        {
                            Id = 122L,
                            X1 = 69,
                            X2 = 125,
                            Y1 = 41,
                            Y2 = 138
                        },
                        new
                        {
                            Id = 123L,
                            X1 = 25,
                            X2 = 171,
                            Y1 = 0,
                            Y2 = 15
                        },
                        new
                        {
                            Id = 124L,
                            X1 = 22,
                            X2 = 132,
                            Y1 = 5,
                            Y2 = 35
                        },
                        new
                        {
                            Id = 125L,
                            X1 = 23,
                            X2 = 144,
                            Y1 = 11,
                            Y2 = 43
                        },
                        new
                        {
                            Id = 126L,
                            X1 = 2,
                            X2 = 139,
                            Y1 = 98,
                            Y2 = 149
                        },
                        new
                        {
                            Id = 127L,
                            X1 = 57,
                            X2 = 113,
                            Y1 = 47,
                            Y2 = 126
                        },
                        new
                        {
                            Id = 128L,
                            X1 = 3,
                            X2 = 169,
                            Y1 = 90,
                            Y2 = 131
                        },
                        new
                        {
                            Id = 129L,
                            X1 = 43,
                            X2 = 46,
                            Y1 = 28,
                            Y2 = 135
                        },
                        new
                        {
                            Id = 130L,
                            X1 = 44,
                            X2 = 145,
                            Y1 = 21,
                            Y2 = 172
                        },
                        new
                        {
                            Id = 131L,
                            X1 = 83,
                            X2 = 124,
                            Y1 = 58,
                            Y2 = 133
                        },
                        new
                        {
                            Id = 132L,
                            X1 = 37,
                            X2 = 75,
                            Y1 = 66,
                            Y2 = 105
                        },
                        new
                        {
                            Id = 133L,
                            X1 = 3,
                            X2 = 66,
                            Y1 = 21,
                            Y2 = 72
                        },
                        new
                        {
                            Id = 134L,
                            X1 = 32,
                            X2 = 71,
                            Y1 = 93,
                            Y2 = 129
                        },
                        new
                        {
                            Id = 135L,
                            X1 = 84,
                            X2 = 175,
                            Y1 = 23,
                            Y2 = 64
                        },
                        new
                        {
                            Id = 136L,
                            X1 = 85,
                            X2 = 188,
                            Y1 = 71,
                            Y2 = 85
                        },
                        new
                        {
                            Id = 137L,
                            X1 = 2,
                            X2 = 174,
                            Y1 = 34,
                            Y2 = 95
                        },
                        new
                        {
                            Id = 138L,
                            X1 = 50,
                            X2 = 187,
                            Y1 = 48,
                            Y2 = 51
                        },
                        new
                        {
                            Id = 139L,
                            X1 = 51,
                            X2 = 87,
                            Y1 = 82,
                            Y2 = 143
                        },
                        new
                        {
                            Id = 140L,
                            X1 = 95,
                            X2 = 106,
                            Y1 = 21,
                            Y2 = 61
                        },
                        new
                        {
                            Id = 141L,
                            X1 = 83,
                            X2 = 94,
                            Y1 = 96,
                            Y2 = 129
                        },
                        new
                        {
                            Id = 142L,
                            X1 = 78,
                            X2 = 178,
                            Y1 = 53,
                            Y2 = 109
                        },
                        new
                        {
                            Id = 143L,
                            X1 = 90,
                            X2 = 97,
                            Y1 = 70,
                            Y2 = 89
                        },
                        new
                        {
                            Id = 144L,
                            X1 = 32,
                            X2 = 142,
                            Y1 = 41,
                            Y2 = 83
                        },
                        new
                        {
                            Id = 145L,
                            X1 = 76,
                            X2 = 85,
                            Y1 = 77,
                            Y2 = 148
                        },
                        new
                        {
                            Id = 146L,
                            X1 = 41,
                            X2 = 86,
                            Y1 = 26,
                            Y2 = 39
                        },
                        new
                        {
                            Id = 147L,
                            X1 = 67,
                            X2 = 76,
                            Y1 = 69,
                            Y2 = 70
                        },
                        new
                        {
                            Id = 148L,
                            X1 = 69,
                            X2 = 163,
                            Y1 = 30,
                            Y2 = 159
                        },
                        new
                        {
                            Id = 149L,
                            X1 = 17,
                            X2 = 126,
                            Y1 = 21,
                            Y2 = 106
                        },
                        new
                        {
                            Id = 150L,
                            X1 = 19,
                            X2 = 98,
                            Y1 = 25,
                            Y2 = 80
                        },
                        new
                        {
                            Id = 151L,
                            X1 = 65,
                            X2 = 165,
                            Y1 = 77,
                            Y2 = 148
                        },
                        new
                        {
                            Id = 152L,
                            X1 = 78,
                            X2 = 146,
                            Y1 = 85,
                            Y2 = 184
                        },
                        new
                        {
                            Id = 153L,
                            X1 = 54,
                            X2 = 147,
                            Y1 = 86,
                            Y2 = 171
                        },
                        new
                        {
                            Id = 154L,
                            X1 = 90,
                            X2 = 167,
                            Y1 = 58,
                            Y2 = 104
                        },
                        new
                        {
                            Id = 155L,
                            X1 = 51,
                            X2 = 147,
                            Y1 = 91,
                            Y2 = 170
                        },
                        new
                        {
                            Id = 156L,
                            X1 = 20,
                            X2 = 103,
                            Y1 = 40,
                            Y2 = 95
                        },
                        new
                        {
                            Id = 157L,
                            X1 = 74,
                            X2 = 171,
                            Y1 = 46,
                            Y2 = 71
                        },
                        new
                        {
                            Id = 158L,
                            X1 = 93,
                            X2 = 158,
                            Y1 = 72,
                            Y2 = 128
                        },
                        new
                        {
                            Id = 159L,
                            X1 = 11,
                            X2 = 196,
                            Y1 = 82,
                            Y2 = 164
                        },
                        new
                        {
                            Id = 160L,
                            X1 = 0,
                            X2 = 66,
                            Y1 = 82,
                            Y2 = 130
                        },
                        new
                        {
                            Id = 161L,
                            X1 = 44,
                            X2 = 103,
                            Y1 = 19,
                            Y2 = 196
                        },
                        new
                        {
                            Id = 162L,
                            X1 = 51,
                            X2 = 105,
                            Y1 = 57,
                            Y2 = 109
                        },
                        new
                        {
                            Id = 163L,
                            X1 = 98,
                            X2 = 120,
                            Y1 = 30,
                            Y2 = 128
                        },
                        new
                        {
                            Id = 164L,
                            X1 = 84,
                            X2 = 180,
                            Y1 = 26,
                            Y2 = 145
                        },
                        new
                        {
                            Id = 165L,
                            X1 = 87,
                            X2 = 123,
                            Y1 = 72,
                            Y2 = 180
                        },
                        new
                        {
                            Id = 166L,
                            X1 = 93,
                            X2 = 133,
                            Y1 = 17,
                            Y2 = 154
                        },
                        new
                        {
                            Id = 167L,
                            X1 = 48,
                            X2 = 55,
                            Y1 = 5,
                            Y2 = 36
                        },
                        new
                        {
                            Id = 168L,
                            X1 = 11,
                            X2 = 63,
                            Y1 = 50,
                            Y2 = 60
                        },
                        new
                        {
                            Id = 169L,
                            X1 = 79,
                            X2 = 134,
                            Y1 = 84,
                            Y2 = 98
                        },
                        new
                        {
                            Id = 170L,
                            X1 = 31,
                            X2 = 130,
                            Y1 = 12,
                            Y2 = 194
                        },
                        new
                        {
                            Id = 171L,
                            X1 = 59,
                            X2 = 113,
                            Y1 = 19,
                            Y2 = 72
                        },
                        new
                        {
                            Id = 172L,
                            X1 = 68,
                            X2 = 156,
                            Y1 = 27,
                            Y2 = 56
                        },
                        new
                        {
                            Id = 173L,
                            X1 = 23,
                            X2 = 195,
                            Y1 = 78,
                            Y2 = 167
                        },
                        new
                        {
                            Id = 174L,
                            X1 = 98,
                            X2 = 153,
                            Y1 = 1,
                            Y2 = 49
                        },
                        new
                        {
                            Id = 175L,
                            X1 = 4,
                            X2 = 30,
                            Y1 = 32,
                            Y2 = 196
                        },
                        new
                        {
                            Id = 176L,
                            X1 = 58,
                            X2 = 78,
                            Y1 = 87,
                            Y2 = 102
                        },
                        new
                        {
                            Id = 177L,
                            X1 = 14,
                            X2 = 130,
                            Y1 = 81,
                            Y2 = 107
                        },
                        new
                        {
                            Id = 178L,
                            X1 = 17,
                            X2 = 27,
                            Y1 = 31,
                            Y2 = 131
                        },
                        new
                        {
                            Id = 179L,
                            X1 = 60,
                            X2 = 197,
                            Y1 = 39,
                            Y2 = 134
                        },
                        new
                        {
                            Id = 180L,
                            X1 = 18,
                            X2 = 23,
                            Y1 = 92,
                            Y2 = 159
                        },
                        new
                        {
                            Id = 181L,
                            X1 = 80,
                            X2 = 199,
                            Y1 = 99,
                            Y2 = 113
                        },
                        new
                        {
                            Id = 182L,
                            X1 = 66,
                            X2 = 85,
                            Y1 = 8,
                            Y2 = 69
                        },
                        new
                        {
                            Id = 183L,
                            X1 = 31,
                            X2 = 35,
                            Y1 = 25,
                            Y2 = 147
                        },
                        new
                        {
                            Id = 184L,
                            X1 = 94,
                            X2 = 148,
                            Y1 = 76,
                            Y2 = 198
                        },
                        new
                        {
                            Id = 185L,
                            X1 = 85,
                            X2 = 121,
                            Y1 = 16,
                            Y2 = 69
                        },
                        new
                        {
                            Id = 186L,
                            X1 = 96,
                            X2 = 103,
                            Y1 = 10,
                            Y2 = 171
                        },
                        new
                        {
                            Id = 187L,
                            X1 = 52,
                            X2 = 86,
                            Y1 = 32,
                            Y2 = 46
                        },
                        new
                        {
                            Id = 188L,
                            X1 = 66,
                            X2 = 104,
                            Y1 = 86,
                            Y2 = 191
                        },
                        new
                        {
                            Id = 189L,
                            X1 = 30,
                            X2 = 82,
                            Y1 = 56,
                            Y2 = 164
                        },
                        new
                        {
                            Id = 190L,
                            X1 = 71,
                            X2 = 156,
                            Y1 = 82,
                            Y2 = 120
                        },
                        new
                        {
                            Id = 191L,
                            X1 = 66,
                            X2 = 138,
                            Y1 = 80,
                            Y2 = 149
                        },
                        new
                        {
                            Id = 192L,
                            X1 = 31,
                            X2 = 60,
                            Y1 = 64,
                            Y2 = 154
                        },
                        new
                        {
                            Id = 193L,
                            X1 = 13,
                            X2 = 24,
                            Y1 = 25,
                            Y2 = 65
                        },
                        new
                        {
                            Id = 194L,
                            X1 = 52,
                            X2 = 177,
                            Y1 = 12,
                            Y2 = 152
                        },
                        new
                        {
                            Id = 195L,
                            X1 = 43,
                            X2 = 109,
                            Y1 = 23,
                            Y2 = 148
                        },
                        new
                        {
                            Id = 196L,
                            X1 = 87,
                            X2 = 167,
                            Y1 = 73,
                            Y2 = 119
                        },
                        new
                        {
                            Id = 197L,
                            X1 = 82,
                            X2 = 105,
                            Y1 = 12,
                            Y2 = 105
                        },
                        new
                        {
                            Id = 198L,
                            X1 = 72,
                            X2 = 115,
                            Y1 = 34,
                            Y2 = 80
                        },
                        new
                        {
                            Id = 199L,
                            X1 = 15,
                            X2 = 137,
                            Y1 = 54,
                            Y2 = 199
                        },
                        new
                        {
                            Id = 200L,
                            X1 = 4,
                            X2 = 126,
                            Y1 = 57,
                            Y2 = 60
                        });
                });

            modelBuilder.Entity("TestTask.Database.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Roles")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User", "User");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "administrator@administrator.com",
                            PasswordHash = "eR3YwtuZPO3KZjmvvpqo0OC8vcZCUpzKC9j/Us+aVOwHJWkgVX+jugi7jCeI4kCxGsB0FOP4xFZO7HIVOI5Juc78aV/ewD5auG5lt6cPaVOOGbjIDbM+0Xcfo8MkpXslgTvxzVK8EU63EWm3rJfDhsOanHANh/uQfYIoLGqwtcBcKgbzgDvaH7nGDZ4bgzEOwShp+fPKwiXZNZPuGQRsN9sEYavwDbr3fNW4AUUeVUnY66mEEFX3Lwd+n905N28YYNUG2Of+aJHQSH9x/u1hdjdwfXukB6eP0863z89x4QCSL9bq3F7CmHOAKyfxR5YSxsgKn+EWKNuBRFOFOdcbS/cumBWC0jvmwhnmLzdy7DLGGDm4ZnSXfEhzXmKMlVuP72CP+lXCvslIiiGDsjn0ZmNlP8gbw4O7Apl6X9KyPV1zJk7RlJazqRr0Yge5u7klPsocKbdLHEoOSdvR/jhLhzXKkhZunmEvvOZFYnPNnl0UX8a5G729uzdxeUghqgXhnLWFgs7nElkQ2EZVTuQv1it9uWrprpKU8YWjv+wXs7LM84EvT3oNmeBrqQUkfaSP773fwP5wULMrgIIO5NP3HzjbuKzgAOU01UMJc/Hm960gAkkBzhYjL9uolf/iJNVJ6ggEhFo+0EjvV4J52eS5fddHX5r3hQSiDK9hrb6LlHo=",
                            Roles = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
